Update component models
adobe-rnd/aem-block-collection-xwalk pull request #2
Opened 2024-08-14 08:15 UTC by mind-adobe

Add component definition / models / filters for Search, Video and Table block

Test URLs:
- Before: https://main--aem-block-collection--adobe.hlx.page
- After: https://update-component-models--aem-block-collection--adobe.hlx.page

2024-08-14 09:27 UTC, msagolj requested changes

2024-08-14 09:27 UTC, msagolj commented on blocks/table/table.js
- add color definition for striped class in table
- no-header for table is not working anymore
- make 2 column width 50/50

2024-08-14 09:27 UTC, msagolj commented on component-models.json
> +        "label": "Image",
use more descriptive label

2024-08-15 15:05 UTC, msagolj approved these changes

2024-08-21 15:13 UTC, buuhuu commented on component-models.json
> +            "name":"Columns",
Why not create a new select for this to change the value of the `filter` property to anything of `table`, `table-3-columns`, `table-4-columns`, ... etc.

2024-08-21 15:13 UTC, buuhuu commented on component-filters.json
> +    "id":"table-2-rows",
probably better call it `table-2-columns`?

2024-08-21 15:13 UTC, buuhuu commented on scripts/editor-support.js
> +function updateTableFilter(block) {
not needed if you change the filter directly with the table's component model

2024-08-30 08:02 UTC, merged